CATEGORY_CHOICES = [
    ("local_dishes", "Local Dishes"),
    ("swallow", "Swallow"),
    ("soups_stews", "Soups & Stews"),
    ("rice", "Rice Dishes"),
    ("pasta", "Pasta"),
    ("grills", "Grills & Barbecue"),
    ("chicken", "Chicken & Turkey"),
    ("shawarma", "Shawarma"),
    ("fast_food", "Fast Food"),
    ("continental", "Continental"),
    ("breakfast", "Breakfast"),
    ("snacks", "Snacks & Pastries"),
    ("desserts", "Desserts"),
    ("salads", "Salads"),
    ("drinks", "Drinks"),
    ("smoothies", "Smoothies & Juices"),
    ("family_packs", "Family Packs"),
]